import { HorseStats, Weather } from './simulation';

export const STARTER_HORSES: HorseStats[] = [
  {
    id: 'thunderbolt',
    name: 'Thunderbolt',
    emoji: '⚡',
    color: '#F59E0B',
    speed: 78,
    stamina: 58,
    acceleration: 82,
    consistency: 65,
    trackPref: 'dirt',
    distancePref: 'sprint',
    jockeyBonus: 5,
    wins: 0,
    races: 0,
    trait: 'fast_start',
    rarity: 'common',
  },
  {
    id: 'midnight',
    name: 'Midnight Star',
    emoji: '🌟',
    color: '#6366F1',
    speed: 78,
    stamina: 88,
    acceleration: 65,
    consistency: 85,
    trackPref: 'turf',
    distancePref: 'long',
    jockeyBonus: 7,
    wins: 0,
    races: 0,
    trait: 'steady_heart',
    rarity: 'rare',
  },
  {
    id: 'crimson',
    name: 'Crimson King',
    emoji: '🔥',
    color: '#EF4444',
    speed: 92,
    stamina: 55,
    acceleration: 80,
    consistency: 60,
    trackPref: 'synthetic',
    distancePref: 'sprint',
    jockeyBonus: 5,
    wins: 0,
    races: 0,
    trait: 'crowd_favorite',
    rarity: 'rare',
  },
  {
    id: 'stormy',
    name: 'Stormy Cloud',
    emoji: '⛈️',
    color: '#64748B',
    speed: 72,
    stamina: 92,
    acceleration: 58,
    consistency: 90,
    trackPref: 'turf',
    distancePref: 'mile',
    jockeyBonus: 8,
    wins: 0,
    races: 0,
    trait: 'iron_will',
    rarity: 'elite',
  },
  {
    id: 'golden',
    name: 'Golden Arrow',
    emoji: '🏹',
    color: '#10B981',
    speed: 80,
    stamina: 75,
    acceleration: 75,
    consistency: 78,
    trackPref: 'dirt',
    distancePref: 'mile',
    jockeyBonus: 6,
    wins: 0,
    races: 0,
    trait: 'closer',
    rarity: 'rare',
  },
  {
    id: 'shadow',
    name: 'Shadow Dancer',
    emoji: '🌙',
    color: '#8B5CF6',
    speed: 88,
    stamina: 70,
    acceleration: 85,
    consistency: 55,
    trackPref: 'synthetic',
    distancePref: 'sprint',
    jockeyBonus: 4,
    wins: 0,
    races: 0,
    trait: 'mud_runner',
    rarity: 'elite',
  },
];

export const RACE_CONFIGS = [
  {
    id: 'novice-sprint',
    name: 'Novice Sprint',
    track: 'dirt' as const,
    distance: 'sprint' as const,
    weather: 'sunny' as Weather,
    entryFee: 50,
    prizePool: 300,
    trophyReward: 20,
    tier: 1,
    description: 'Fast gate speed matters more than deep stamina here.',
  },
  {
    id: 'turf-mile',
    name: 'Turf Mile Classic',
    track: 'turf' as const,
    distance: 'mile' as const,
    weather: 'overcast' as Weather,
    entryFee: 100,
    prizePool: 600,
    trophyReward: 35,
    tier: 2,
    description: 'Balanced runners and reliable horses do well on this line.',
  },
  {
    id: 'grand-marathon',
    name: 'Grand Marathon',
    track: 'turf' as const,
    distance: 'long' as const,
    weather: 'windy' as Weather,
    entryFee: 200,
    prizePool: 1200,
    trophyReward: 55,
    tier: 3,
    description: 'A stamina grinder where late closers can steal the finish.',
  },
  {
    id: 'dirt-dash',
    name: 'Dirt Dash',
    track: 'dirt' as const,
    distance: 'sprint' as const,
    weather: 'rain' as Weather,
    entryFee: 75,
    prizePool: 450,
    trophyReward: 28,
    tier: 2,
    description: 'Heavy ground rewards mud runners and disciplined jockeys.',
  },
  {
    id: 'synth-mile',
    name: 'Synthetic Mile',
    track: 'synthetic' as const,
    distance: 'mile' as const,
    weather: 'sunny' as Weather,
    entryFee: 150,
    prizePool: 900,
    trophyReward: 45,
    tier: 3,
    description: 'Consistency and pace control are everything in this event.',
  },
] as const;
